# @package _global_

size: "6.7b"
model_path: 'deepseek-ai/deepseek-coder-${size}-base'
model_short_name: "deepseek-coder-6.7b"
lm_prefix_tokens: ""
lm_suffix_tokens: ""
prefix_tokens: "<｜fim▁begin｜>"
middle_tokens: "<｜fim▁hole｜>"
suffix_tokens: "<｜fim▁end｜>"
max_context_length: 7500
model_kwargs:
  use_flash_attention_2: True
